### ISSUE TITLE
DeprecationWarning: collections

### ISSUE THREAD

**Issue by martinwangjun** [pymssql/pymssql#594]
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Is it possible to fix this warning issue? Thanks.

**Comment by martinwangjun** [comment]
Sorry. It is submitted by another guy.

**Comment by AlexHagerman** [comment]
This is fixed in stable 2.1.x by #592 and will be included in the next release.

**Comment by martinwangjun** [comment]
Many thanks. pymssql is amazing!

**Comment by rafaelcs** [comment]
Hello,

I'm using Python version 3.7.2 and pymssql version 2.1.4 but still getting the same error. Any help to fix it?

**Comment by AlexHagerman** [comment]
You can pull and build the branch that has #592 merged or implement that change on your local.

**Comment by rafaelcs** [comment]
I'm using `pip install pymssql` to install the package. Is there any deadline to release this fix without having to fix locally? Thanks @AlexHagerman

**Comment by AlexHagerman** [comment]
@rafaelcs pymssql doesn't have much in the way of active maintainer resources right now. This along with freetds 7.4 support, openssl, branch management and a couple other items could use some individuals to facilitate release management, code review, pull request and road mapping.
